/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootLayoutImport } from './routes/_root-layout'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as RootLayoutIndexImport } from './routes/_root-layout/index'
import { Route as RootLayoutProfileImport } from './routes/_root-layout/profile'
import { Route as RootLayoutAboutImport } from './routes/_root-layout/about'
import { Route as AuthLayoutSignInImport } from './routes/_auth-layout/sign-in'
import { Route as AuthLayoutCreateFirstUserImport } from './routes/_auth-layout/create-first-user'
import { Route as RootLayoutProductsIndexImport } from './routes/_root-layout/products/index'
import { Route as RootLayoutProductsNewImport } from './routes/_root-layout/products/new'
import { Route as RootLayoutProductsIdImport } from './routes/_root-layout/products/$id'

// Create/Update Routes

const RootLayoutRoute = RootLayoutImport.update({
  id: '/_root-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutProfileRoute = RootLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutAboutRoute = RootLayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => RootLayoutRoute,
} as any)

const AuthLayoutSignInRoute = AuthLayoutSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutCreateFirstUserRoute = AuthLayoutCreateFirstUserImport.update({
  path: '/create-first-user',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const RootLayoutProductsIndexRoute = RootLayoutProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutProductsNewRoute = RootLayoutProductsNewImport.update({
  path: '/products/new',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutProductsIdRoute = RootLayoutProductsIdImport.update({
  path: '/products/$id',
  getParentRoute: () => RootLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_root-layout': {
      id: '/_root-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/create-first-user': {
      id: '/_auth-layout/create-first-user'
      path: '/create-first-user'
      fullPath: '/create-first-user'
      preLoaderRoute: typeof AuthLayoutCreateFirstUserImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/sign-in': {
      id: '/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_root-layout/about': {
      id: '/_root-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootLayoutAboutImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/profile': {
      id: '/_root-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof RootLayoutProfileImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/': {
      id: '/_root-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/products/$id': {
      id: '/_root-layout/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof RootLayoutProductsIdImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/products/new': {
      id: '/_root-layout/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof RootLayoutProductsNewImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/products/': {
      id: '/_root-layout/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof RootLayoutProductsIndexImport
      parentRoute: typeof RootLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutCreateFirstUserRoute: typeof AuthLayoutCreateFirstUserRoute
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCreateFirstUserRoute: AuthLayoutCreateFirstUserRoute,
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface RootLayoutRouteChildren {
  RootLayoutAboutRoute: typeof RootLayoutAboutRoute
  RootLayoutProfileRoute: typeof RootLayoutProfileRoute
  RootLayoutIndexRoute: typeof RootLayoutIndexRoute
  RootLayoutProductsIdRoute: typeof RootLayoutProductsIdRoute
  RootLayoutProductsNewRoute: typeof RootLayoutProductsNewRoute
  RootLayoutProductsIndexRoute: typeof RootLayoutProductsIndexRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutAboutRoute: RootLayoutAboutRoute,
  RootLayoutProfileRoute: RootLayoutProfileRoute,
  RootLayoutIndexRoute: RootLayoutIndexRoute,
  RootLayoutProductsIdRoute: RootLayoutProductsIdRoute,
  RootLayoutProductsNewRoute: RootLayoutProductsNewRoute,
  RootLayoutProductsIndexRoute: RootLayoutProductsIndexRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof RootLayoutRouteWithChildren
  '/create-first-user': typeof AuthLayoutCreateFirstUserRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/about': typeof RootLayoutAboutRoute
  '/profile': typeof RootLayoutProfileRoute
  '/': typeof RootLayoutIndexRoute
  '/products/$id': typeof RootLayoutProductsIdRoute
  '/products/new': typeof RootLayoutProductsNewRoute
  '/products': typeof RootLayoutProductsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthLayoutRouteWithChildren
  '/create-first-user': typeof AuthLayoutCreateFirstUserRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/about': typeof RootLayoutAboutRoute
  '/profile': typeof RootLayoutProfileRoute
  '/': typeof RootLayoutIndexRoute
  '/products/$id': typeof RootLayoutProductsIdRoute
  '/products/new': typeof RootLayoutProductsNewRoute
  '/products': typeof RootLayoutProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_root-layout': typeof RootLayoutRouteWithChildren
  '/_auth-layout/create-first-user': typeof AuthLayoutCreateFirstUserRoute
  '/_auth-layout/sign-in': typeof AuthLayoutSignInRoute
  '/_root-layout/about': typeof RootLayoutAboutRoute
  '/_root-layout/profile': typeof RootLayoutProfileRoute
  '/_root-layout/': typeof RootLayoutIndexRoute
  '/_root-layout/products/$id': typeof RootLayoutProductsIdRoute
  '/_root-layout/products/new': typeof RootLayoutProductsNewRoute
  '/_root-layout/products/': typeof RootLayoutProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/create-first-user'
    | '/sign-in'
    | '/about'
    | '/profile'
    | '/'
    | '/products/$id'
    | '/products/new'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/create-first-user'
    | '/sign-in'
    | '/about'
    | '/profile'
    | '/'
    | '/products/$id'
    | '/products/new'
    | '/products'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/_root-layout'
    | '/_auth-layout/create-first-user'
    | '/_auth-layout/sign-in'
    | '/_root-layout/about'
    | '/_root-layout/profile'
    | '/_root-layout/'
    | '/_root-layout/products/$id'
    | '/_root-layout/products/new'
    | '/_root-layout/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  RootLayoutRoute: RootLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/_root-layout"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout.tsx",
      "children": [
        "/_auth-layout/create-first-user",
        "/_auth-layout/sign-in"
      ]
    },
    "/_root-layout": {
      "filePath": "_root-layout.tsx",
      "children": [
        "/_root-layout/about",
        "/_root-layout/profile",
        "/_root-layout/",
        "/_root-layout/products/$id",
        "/_root-layout/products/new",
        "/_root-layout/products/"
      ]
    },
    "/_auth-layout/create-first-user": {
      "filePath": "_auth-layout/create-first-user.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/sign-in": {
      "filePath": "_auth-layout/sign-in.tsx",
      "parent": "/_auth-layout"
    },
    "/_root-layout/about": {
      "filePath": "_root-layout/about.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/profile": {
      "filePath": "_root-layout/profile.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/": {
      "filePath": "_root-layout/index.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/products/$id": {
      "filePath": "_root-layout/products/$id.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/products/new": {
      "filePath": "_root-layout/products/new.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/products/": {
      "filePath": "_root-layout/products/index.tsx",
      "parent": "/_root-layout"
    }
  }
}
ROUTE_MANIFEST_END */
