import "~/styles/globals.css";

import { Poppins } from "next/font/google";
import { type Metadata } from "next";
import Providers from "~/lib/providers";
import { cn } from "@nexcom/ui/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
